### ISSUE TITLE
What's the problem for "RangeError (index): Invalid value: Valid value range is empty: 0"

### ISSUE THREAD

**Issue by debugerer** [aloisdeniel/flutter_sheet_localization#10]
Hi, 
Thanks for you sharing a so Powerful tools. that's great.
But when i first use, it report the following error. I have  retry Several times, but no luck. I can't found the tool source in .drat_tool folder to trace the issue. Could u give me an idea? thank you very much.

[INFO] 4.2s elapsed, 1/12 actions completed.
[INFO] 5.3s elapsed, 1/12 actions completed.
[INFO] 6.5s elapsed, 1/12 actions completed.
[INFO] flutter_sheet_localization_generator:flutter_sheet_localization on lib/localizations.dart:Downloading csv from Google sheet url "https://docs.google.com/spreadsheets/d/XXX/export?format=csv&id=XXX&gid=0" ...
[INFO] 12.9s elapsed, 3/12 actions completed.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on **lib/localizations.dart:
Error running SheetLocalizationGenerator
RangeError (index): Invalid value: Valid value range is empty: 0**
[INFO] Running build completed, took 13.8s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 42ms

[SEVERE] Failed after 13.8s
pub finished with exit code 1

**Comment by debugerer** [comment]
I found the reason, this is a very good tool, thank you.

**Comment by aloisdeniel** [comment]
Do you have details on the error ? 

I definitively still have to make errors a lot more clear and readable!

**Comment by illuminated** [comment]
> I found the reason, this is a very good tool, thank you.

Hey, @debugerer, can you please share the solution you have found? I'm struggling with the same thing.

**Comment by illuminated** [comment]
The issue here is the following:
the linked example Google sheet has some keys with conditions, like `time.hour(Plural.one)`. When I opened the linked example sheet, the dynamic part was extracted into a separate column and that creates the error described in the first post and the one I was getting as well:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/295242/96202111-9ff66680-0f5e-11eb-92ec-279d618d9582.png">
